[package]
name = "gargoyle-web-monitor"
version = "0.1.0"
edition = "2021"
authors = ["Mason Soroka-Gill <Mordinel@pm.me>"]

[dependencies]
gargoyle = "0.1.5"
log = "0.4.21"
reqwest = { version = "0.12.4", features = ["blocking"] }
